version: '3.3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always

  base-api:
    container_name: base-api
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    image: base-api
    restart: always
    ports:
      - 3333:3333

